[package]
name = "gitcore"
version = "1.4.0"
edition = "2024"
description = "A secure, zero-friction Git identity manager for developers who juggle multiple accounts."
license = "MIT"
homepage = "https://github.com/shedrackgodstime/gitcore"
repository = "https://github.com/shedrackgodstime/gitcore"
keywords = ["git", "ssh", "identity", "account-manager", "cli"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
colored = "2"
aes-gcm = "0.10"
argon2 = "0.5"
rand = "0.8"
rpassword = "7"
thiserror = "2"

[dev-dependencies]
tempfile = "3"

[lib]
name = "gitcore"
path = "src/lib.rs"

[[bin]]
name = "gitcore"
path = "src/bin/gitcore/main.rs"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
