use clap::{Parser, Subcommand};
use colored::Colorize;
use serde::{Deserialize, Serialize};
use std::fs;
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Account {
    pub name: String,
    pub platform: Platform,
    pub key_path: String,
    pub host_alias: String,
    pub username: String,
    pub email: String,
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum Platform {
    Github,
    Gitlab,
    Codeberg,
    Bitbucket,
}

impl Platform {
    fn host(&self) -> &str {
        match self {
            Platform::Github => "github.com",
            Platform::Gitlab => "gitlab.com",
            Platform::Codeberg => "codeberg.org",
            Platform::Bitbucket => "bitbucket.org",
        }
    }

    fn from_str(s: &str) -> Option<Platform> {
        match s.to_lowercase().as_str() {
            "github" => Some(Platform::Github),
            "gitlab" => Some(Platform::Gitlab),
            "codeberg" => Some(Platform::Codeberg),
            "bitbucket" | "bb" => Some(Platform::Bitbucket),
            _ => None,
        }
    }
}

fn is_valid_account_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
}

fn validate_accounts(accounts: &[Account]) -> Result<(), String> {
    let mut names = std::collections::HashSet::new();
    let mut aliases = std::collections::HashSet::new();

    for acc in accounts {
        if !is_valid_account_name(&acc.name) {
            return Err(format!("Invalid account name '{}'", acc.name));
        }

        if acc.username.trim().is_empty() {
            return Err(format!("Account '{}' has an empty username", acc.name));
        }

        if acc.email.trim().is_empty() {
            return Err(format!("Account '{}' has an empty email", acc.name));
        }

        let normalized_name = acc.name.to_ascii_lowercase();
        if !names.insert(normalized_name) {
            return Err(format!("Duplicate account name '{}'", acc.name));
        }

        let normalized_alias = acc.host_alias.to_ascii_lowercase();
        if !aliases.insert(normalized_alias) {
            return Err(format!("Duplicate host alias '{}'", acc.host_alias));
        }
    }

    Ok(())
}

fn command_error(command: &str, output: &Output) -> io::Error {
    let stderr = String::from_utf8_lossy(&output.stderr).trim().to_string();
    let stdout = String::from_utf8_lossy(&output.stdout).trim().to_string();
    let detail = if !stderr.is_empty() {
        stderr
    } else if !stdout.is_empty() {
        stdout
    } else {
        format!("exit status: {}", output.status)
    };

    io::Error::other(format!("{command}: {detail}"))
}

fn run_command(command: &str, args: &[&str]) -> io::Result<Output> {
    let output = Command::new(command).args(args).output()?;
    if output.status.success() {
        Ok(output)
    } else {
        Err(command_error(command, &output))
    }
}

fn run_git(args: &[&str]) -> io::Result<Output> {
    run_command("git", args)
}

fn ensure_git_repository(path: &Path) -> bool {
    run_git(&["-C", path.to_str().unwrap_or("."), "rev-parse", "--git-dir"]).is_ok()
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct GityConfig {
    pub accounts: Vec<Account>,
}

fn get_ssh_dir() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("~"))
        .join(".ssh")
}

fn get_config_path() -> PathBuf {
    dirs::config_dir()
        .unwrap_or_else(|| PathBuf::from("~/.config"))
        .join("gity")
        .join("config.json")
}

fn load_config() -> GityConfig {
    let path = get_config_path();
    if path.exists() {
        let content = fs::read_to_string(&path).unwrap_or_default();
        serde_json::from_str(&content).unwrap_or_default()
    } else {
        GityConfig::default()
    }
}

fn save_config(config: &GityConfig) -> io::Result<()> {
    let path = get_config_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let content = serde_json::to_string_pretty(config)?;
    fs::write(path, content)
}

fn update_ssh_config(accounts: &[Account]) -> io::Result<()> {
    let ssh_dir = get_ssh_dir();
    fs::create_dir_all(&ssh_dir)?;
    let config_path = ssh_dir.join("config");
    const START_MARKER: &str = "# >>> gity managed block >>>";
    const END_MARKER: &str = "# <<< gity managed block <<<";

    let mut managed_block = String::new();
    managed_block.push_str("# Generated by gity - DO NOT EDIT MANUALLY\n");
    managed_block.push_str(START_MARKER);
    managed_block.push('\n');

    for acc in accounts {
        managed_block.push_str(&format!("Host {}\n", acc.host_alias));
        managed_block.push_str(&format!("  HostName {}\n", acc.platform.host()));
        managed_block.push_str("  User git\n");
        managed_block.push_str(&format!("  IdentityFile ~/.ssh/{}\n", acc.key_path));
        managed_block.push_str("  AddKeysToAgent yes\n");
        managed_block.push_str("  IdentitiesOnly yes\n\n");
    }

    managed_block.push_str(END_MARKER);
    managed_block.push('\n');

    let existing = fs::read_to_string(&config_path).unwrap_or_default();
    let new_content = if let Some(start) = existing.find(START_MARKER) {
        if let Some(end_rel) = existing[start..].find(END_MARKER) {
            let end = start + end_rel + END_MARKER.len();
            let before = existing[..start].trim_end();
            let after = existing[end..].trim_start();

            let mut merged = String::new();
            if !before.is_empty() {
                merged.push_str(before);
                merged.push_str("\n\n");
            }
            merged.push_str(&managed_block);
            if !after.is_empty() {
                merged.push('\n');
                merged.push_str(after);
                if !merged.ends_with('\n') {
                    merged.push('\n');
                }
            }
            merged
        } else {
            format!("{}\n{}", existing.trim_end(), managed_block)
        }
    } else if existing.trim().is_empty() {
        managed_block.clone()
    } else {
        format!("{}\n\n{}", existing.trim_end(), managed_block)
    };

    fs::write(config_path, new_content)?;
    println!("{}", "✓ SSH config updated".green());
    Ok(())
}

fn generate_ssh_key(_name: &str, key_path: &str, email: &str) -> io::Result<String> {
    let ssh_dir = get_ssh_dir();
    let key_full = ssh_dir.join(key_path);

    if key_full.exists() {
        println!("{}", "Key already exists, using existing key".yellow());
    } else {
        println!("{}", "Generating SSH key...".cyan());
        run_command(
            "ssh-keygen",
            &[
                "-t",
                "ed25519",
                "-f",
                key_full.to_str().unwrap(),
                "-N",
                "",
                "-C",
                email,
            ],
        )?;
        println!("{}", "✓ SSH key generated".green());
    }

    let pub_key_path = ssh_dir.join(format!("{}.pub", key_path));
    let pub_key = fs::read_to_string(pub_key_path)?;
    Ok(pub_key)
}

#[derive(Parser)]
#[command(name = "gity")]
#[command(version = "1.0.0")]
#[command(about = "Manage multiple Git accounts safely with SSH keys", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    /// Add a new git account (creates SSH key + config)
    /// Add a new git account (prompts if name/platform not given)
    /// Usage: gity add [name] [platform]
    Add {
        name: Option<String>,
        platform: Option<String>,
    },

    /// List all configured accounts with usage instructions
    List,

    /// Clone a repo using a specific account (auto-sets git config)
    /// Usage: gity clone <repo_url>
    Clone { repo: Option<String> },

    /// Test SSH connection (use host_alias like github-work)
    /// Usage: gity test github-work
    Test { name: Option<String> },

    /// Manage git remotes for repositories
    Remote {
        #[command(subcommand)]
        subcommand: RemoteCommands,
    },

    /// Export configuration (for backup or moving to another PC)
    Export,

    /// Import configuration from a file or stdin
    Import { file: Option<String> },

    /// Remove an account from gity config (prompts if no name given)
    Remove { name: Option<String> },
}

#[derive(Subcommand)]
enum RemoteCommands {
    /// Add a remote URL using a specific account
    Add { repo_url: Option<String> },

    /// Switch existing remote to use a different account
    Switch { account: Option<String> },
}

fn main() -> io::Result<()> {
    let cli = Cli::parse();

    match cli.command {
        Commands::Add { name, platform } => {
            let name = if let Some(n) = name {
                n
            } else {
                print!("Enter account name: ");
                io::stdout().flush()?;
                let mut n = String::new();
                io::stdin().read_line(&mut n)?;
                n.trim().to_string()
            };

            let platform = if let Some(p) = platform {
                match Platform::from_str(&p) {
                    Some(pl) => pl,
                    None => {
                        eprintln!(
                            "{}",
                            "Invalid platform. Use: github, gitlab, codeberg, bitbucket".red()
                        );
                        return Ok(());
                    }
                }
            } else {
                print!("Enter platform (github/gitlab/codeberg/bitbucket): ");
                io::stdout().flush()?;
                let mut p = String::new();
                io::stdin().read_line(&mut p)?;
                match Platform::from_str(p.trim()) {
                    Some(pl) => pl,
                    None => {
                        eprintln!(
                            "{}",
                            "Invalid platform. Use: github, gitlab, codeberg, bitbucket".red()
                        );
                        return Ok(());
                    }
                }
            };

            print!("Enter your git username (for commits): ");
            io::stdout().flush()?;
            let mut username = String::new();
            io::stdin().read_line(&mut username)?;
            let username = username.trim();

            print!("Enter your email (for SSH key + commits): ");
            io::stdout().flush()?;
            let mut email = String::new();
            io::stdin().read_line(&mut email)?;
            let email = email.trim();

            let key_path = format!("id_ed25519_{}", name);
            let host_alias = format!("{}-{}", platform.host().split('.').next().unwrap(), name);

            let mut config = load_config();

            if !is_valid_account_name(&name) {
                eprintln!(
                    "{} Account name must use only letters, numbers, '-' or '_'.",
                    "✗".red()
                );
                return Ok(());
            }

            if username.is_empty() {
                eprintln!("{}", "✗ Username cannot be empty.".red());
                return Ok(());
            }

            if email.is_empty() {
                eprintln!("{}", "✗ Email cannot be empty.".red());
                return Ok(());
            }

            if config
                .accounts
                .iter()
                .any(|a| a.name.eq_ignore_ascii_case(&name))
            {
                eprintln!(
                    "{} Account '{}' already exists. Use 'gity remove {}' first.",
                    "✗".red(),
                    name,
                    name
                );
                return Ok(());
            }

            if config
                .accounts
                .iter()
                .any(|a| a.host_alias.eq_ignore_ascii_case(&host_alias))
            {
                eprintln!(
                    "{} Host alias '{}' already exists. Choose a different account name.",
                    "✗".red(),
                    host_alias
                );
                return Ok(());
            }

            let pub_key = generate_ssh_key(&name, &key_path, email)?;

            let account = Account {
                name: name.clone(),
                platform: platform.clone(),
                key_path,
                host_alias: host_alias.clone(),
                username: username.to_string(),
                email: email.to_string(),
            };

            config.accounts.push(account);
            save_config(&config)?;
            update_ssh_config(&config.accounts)?;

            println!();
            println!(
                "{}",
                "┌─────────────────────────────────────────────────┐".cyan()
            );
            println!(
                "{}",
                "│           Account Added Successfully!           │".cyan()
            );
            println!(
                "{}",
                "└─────────────────────────────────────────────────┘".cyan()
            );
            println!();
            println!("  Name:     {}", name.bold());
            println!("  Platform: {:?}", platform);
            println!("  Use:      git clone git@{}:user/repo.git", host_alias);
            println!();
            println!("{}", "─".repeat(51));
            println!();
            println!("{}", "  1. ADD SSH KEY TO YOUR PLATFORM".yellow().bold());
            println!();
            println!("  {}", pub_key);
            println!();
            println!(
                "  Open: {}",
                match platform {
                    Platform::Github => "https://github.com/settings/keys",
                    Platform::Gitlab => "https://gitlab.com/-/profile/keys",
                    Platform::Codeberg => "https://codeberg.org/user/keys",
                    Platform::Bitbucket => "https://bitbucket.org/account/settings/ssh-keys/",
                }
                .cyan()
            );
            println!();
            println!("{}", "─".repeat(51));
            println!();
            println!("{}", "  2. TEST CONNECTION".yellow().bold());
            println!();
            println!("  Run: {}", format!("gity test {}", host_alias).cyan());
            println!();
            println!("{}", "─".repeat(51));
            println!();
            println!("{}", "  3. USAGE".yellow().bold());
            println!();
            println!("  Clone:  git clone git@{}:username/repo.git", host_alias);
            println!("  Remote: gity remote add");
            println!();
        }

        Commands::List => {
            let config = load_config();
            if config.accounts.is_empty() {
                println!(
                    "{}",
                    "No accounts configured. Run 'gity add <name> <platform>'".yellow()
                );
                return Ok(());
            }

            println!(
                "{}",
                "╔═══════════════════════════════════════════════════╗".cyan()
            );
            println!(
                "{}",
                "║           Configured Git Accounts                 ║".cyan()
            );
            println!(
                "{}",
                "╚═══════════════════════════════════════════════════╝".cyan()
            );
            println!();

            for (i, acc) in config.accounts.iter().enumerate() {
                println!("{} [{}] {}", "●".green(), i + 1, acc.name.bold());
                println!("   Platform: {:?}", acc.platform);
                println!("   Host:     {}", acc.host_alias);
                println!("   Key:      ~/.ssh/{}", acc.key_path);
                println!("   User:     {}", acc.username);
                println!("   Email:    {}", acc.email);
                println!(
                    "   Use:      git clone git@{}:user/repo.git",
                    acc.host_alias
                );
                println!();
            }
        }

        Commands::Clone { repo } => {
            let config = load_config();
            if config.accounts.is_empty() {
                println!("{}", "No accounts. Run 'gity add' first".red());
                return Ok(());
            }

            let preloaded: Option<(String, &Account)> = if let Some(url) = repo.clone() {
                if let Some(stripped) = url.strip_prefix("git@") {
                    if let Some(colon_pos) = stripped.find(':') {
                        let alias = &stripped[..colon_pos];
                        if let Some(found) = config.accounts.iter().find(|a| a.host_alias == alias)
                        {
                            Some((url, found))
                        } else {
                            None
                        }
                    } else {
                        None
                    }
                } else {
                    None
                }
            } else {
                None
            };

            if let Some((url, acc)) = preloaded {
                let converted = convert_to_host(&url, &acc.host_alias);
                println!(
                    "{}",
                    format!("  Using account: {} ({})", acc.name, acc.host_alias).cyan()
                );
                println!("  Cloning: {}", converted);

                let clone_dir = std::env::current_dir()
                    .unwrap_or_else(|_| PathBuf::from("."))
                    .join(
                        url.split('/')
                            .next_back()
                            .unwrap_or("repo")
                            .trim_end_matches(".git"),
                    );

                if clone_dir.exists() {
                    if !ensure_git_repository(&clone_dir) {
                        println!("{}", "⚠ Directory exists but not a git repository.".red());
                        return Ok(());
                    }
                } else {
                    if let Err(err) = run_git(&["clone", &converted]) {
                        println!("{}", "✗ Clone failed".red());
                        println!("   {}", err);
                        return Ok(());
                    }
                }

                std::env::set_current_dir(&clone_dir).ok();
                if let Err(err) = set_git_config(&acc.username, &acc.email) {
                    println!(
                        "{}",
                        "✗ Clone succeeded, but git config update failed".red()
                    );
                    println!("   {}", err);
                    return Ok(());
                }
                println!("{}", "✓ Cloned with git config:".green());
                println!("  user.name  = {}", acc.username);
                println!("  user.email = {}", acc.email);
                return Ok(());
            }

            println!("{}", "Select account to use:".cyan());
            for (i, acc) in config.accounts.iter().enumerate() {
                println!(
                    "  [{}] {} ({} - {:?})",
                    i + 1,
                    acc.name.bold(),
                    acc.username,
                    acc.platform
                );
            }
            print!("\nEnter number (1-{}): ", config.accounts.len());
            io::stdout().flush()?;
            let mut input = String::new();
            io::stdin().read_line(&mut input)?;
            let choice: usize = input.trim().parse().unwrap_or(0);

            if choice == 0 || choice > config.accounts.len() {
                println!("{}", "Invalid selection".red());
                return Ok(());
            }

            let acc = &config.accounts[choice - 1];
            let repo_url = repo.unwrap_or_else(|| {
                print!("Enter repository URL: ");
                io::stdout().flush().unwrap();
                let mut url = String::new();
                io::stdin().read_line(&mut url).unwrap();
                url.trim().to_string()
            });

            let converted = convert_to_host(&repo_url, &acc.host_alias);

            println!("\n{}", "Cloning with account:".yellow());
            println!("  Account: {}", acc.name);
            println!("  Email:   {}", acc.email);
            println!("  Remote:  {}", converted);
            println!();

            let clone_dir = std::env::current_dir()
                .unwrap_or_else(|_| PathBuf::from("."))
                .join(
                    repo_url
                        .split('/')
                        .next_back()
                        .unwrap_or("repo")
                        .trim_end_matches(".git"),
                );

            if clone_dir.exists() {
                if !ensure_git_repository(&clone_dir) {
                    println!("{}", "⚠ Directory exists but not a git repository.".red());
                    return Ok(());
                }
                println!(
                    "{}",
                    "Directory already exists. Using existing repo.".yellow()
                );
                if let Err(err) = run_git_remote_add(&converted) {
                    println!("{}", "✗ Failed to configure origin remote".red());
                    println!("   {}", err);
                    return Ok(());
                }
            } else {
                println!("{}", "Running: git clone".cyan());
                if let Err(err) = run_git(&["clone", &converted]) {
                    println!("{}", "✗ Clone failed".red());
                    println!("   {}", err);
                    return Ok(());
                }
            }

            let target_dir = if clone_dir.exists() {
                clone_dir.clone()
            } else {
                std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."))
            };

            std::env::set_current_dir(&target_dir).ok();

            if let Err(err) = set_git_config(&acc.username, &acc.email) {
                println!(
                    "{}",
                    "✗ Clone succeeded, but git config update failed".red()
                );
                println!("   {}", err);
                return Ok(());
            }
            println!("{}", "✓ Cloned and git config set:".green());
            println!("  user.name  = {}", acc.username);
            println!("  user.email = {}", acc.email);
        }

        Commands::Test { name } => {
            let config = load_config();
            if config.accounts.is_empty() {
                println!("{}", "No accounts configured. Run 'gity add' first".red());
                return Ok(());
            }

            let target = if let Some(n) = name {
                config
                    .accounts
                    .iter()
                    .find(|a| a.name == n || a.host_alias.starts_with(&n))
            } else {
                println!("{}", "Select account to test:".cyan());
                for (i, acc) in config.accounts.iter().enumerate() {
                    println!(
                        "  [{}] {} ({} - {:?})",
                        i + 1,
                        acc.name,
                        acc.username,
                        acc.platform
                    );
                }
                print!("\nEnter number (1-{}): ", config.accounts.len());
                io::stdout().flush()?;
                let mut input = String::new();
                io::stdin().read_line(&mut input)?;
                let choice: usize = input.trim().parse().unwrap_or(0);
                if choice == 0 || choice > config.accounts.len() {
                    None
                } else {
                    Some(&config.accounts[choice - 1])
                }
            };

            if let Some(acc) = target {
                println!(
                    "\n{}",
                    format!("Testing connection to {}...", acc.platform.host()).cyan()
                );
                let output = Command::new("ssh")
                    .args([
                        "-o",
                        "BatchMode=yes",
                        "-o",
                        "ConnectTimeout=10",
                        "-T",
                        &acc.host_alias,
                    ])
                    .output();

                match output {
                    Ok(out) => {
                        let stderr = String::from_utf8_lossy(&out.stderr);
                        if stderr.contains("successfully authenticated") || stderr.contains("Hi") {
                            println!("{}", "✓ Connection successful!".green());
                            println!("   {}", stderr.trim());
                        } else if out.status.success() {
                            println!("{}", "✓ Connected (but no shell access)".green());
                        } else {
                            println!("{}", "✗ Connection failed".red());
                            let detail = stderr.trim();
                            if detail.is_empty() {
                                println!("   exit status: {}", out.status);
                            } else {
                                println!("   {}", detail);
                            }
                        }
                    }
                    Err(e) => {
                        println!("{} {}", "✗ Error:".red(), e);
                    }
                }
            }
        }

        Commands::Remote { subcommand } => match subcommand {
            RemoteCommands::Add { repo_url } => {
                let git_check = Command::new("git")
                    .args(["rev-parse", "--git-dir"])
                    .output();
                if git_check.is_err()
                    || !git_check
                        .as_ref()
                        .map(|o| o.status.success())
                        .unwrap_or(false)
                {
                    println!("{}", "⚠ Not a git repository. Run 'git init' first.".red());
                    return Ok(());
                }

                let config = load_config();
                if config.accounts.is_empty() {
                    println!("{}", "No accounts. Add one first with 'gity add'".red());
                    return Ok(());
                }

                let preloaded: Option<(String, &Account)> = if let Some(url) = repo_url.clone() {
                    if let Some(stripped) = url.strip_prefix("git@") {
                        if let Some(colon_pos) = stripped.find(':') {
                            let alias = &stripped[..colon_pos];
                            if let Some(found) =
                                config.accounts.iter().find(|a| a.host_alias == alias)
                            {
                                Some((url, found))
                            } else {
                                None
                            }
                        } else {
                            None
                        }
                    } else {
                        None
                    }
                } else {
                    None
                };

                if let Some((url, acc)) = preloaded {
                    let converted = convert_to_host(&url, &acc.host_alias);
                    if let Err(err) = set_git_config(&acc.username, &acc.email) {
                        println!("{}", "✗ Failed to set git config".red());
                        println!("   {}", err);
                        return Ok(());
                    }
                    if let Err(err) = run_git_remote_add(&converted) {
                        println!("{}", "✗ Failed to configure origin remote".red());
                        println!("   {}", err);
                        return Ok(());
                    }
                    print_result(&converted, &acc.username, &acc.email);
                    return Ok(());
                }

                let manual_url = repo_url.clone();

                println!("{}", "Select an account to use:".cyan());
                for (i, acc_item) in config.accounts.iter().enumerate() {
                    println!(
                        "  [{}] {} ({} - {:?})",
                        i + 1,
                        acc_item.name,
                        acc_item.username,
                        acc_item.platform
                    );
                }
                print!("\nEnter number (1-{}): ", config.accounts.len());
                io::stdout().flush()?;
                let mut input = String::new();
                io::stdin().read_line(&mut input)?;
                let choice: usize = input.trim().parse().unwrap_or(0);
                if choice == 0 || choice > config.accounts.len() {
                    println!("{}", "Invalid selection".red());
                    return Ok(());
                }

                let selected_acc = &config.accounts[choice - 1];
                let final_repo = manual_url.unwrap_or_else(|| {
                    print!("Enter repository URL: ");
                    io::stdout().flush().unwrap();
                    let mut url = String::new();
                    io::stdin().read_line(&mut url).unwrap();
                    url.trim().to_string()
                });

                let converted = convert_to_host(&final_repo, &selected_acc.host_alias);
                if let Err(err) = set_git_config(&selected_acc.username, &selected_acc.email) {
                    println!("{}", "✗ Failed to set git config".red());
                    println!("   {}", err);
                    return Ok(());
                }
                if let Err(err) = run_git_remote_add(&converted) {
                    println!("{}", "✗ Failed to configure origin remote".red());
                    println!("   {}", err);
                    return Ok(());
                }
                print_result(&converted, &selected_acc.username, &selected_acc.email);
            }

            RemoteCommands::Switch { account } => {
                let git_check = Command::new("git")
                    .args(["rev-parse", "--git-dir"])
                    .output();
                if git_check.is_err()
                    || !git_check
                        .as_ref()
                        .map(|o| o.status.success())
                        .unwrap_or(false)
                {
                    println!("{}", "⚠ Not a git repository.".red());
                    return Ok(());
                }

                let config = load_config();
                if config.accounts.is_empty() {
                    println!("{}", "No accounts configured".red());
                    return Ok(());
                }

                let target = if let Some(name) = account {
                    config
                        .accounts
                        .iter()
                        .find(|a| a.name == name || a.host_alias.starts_with(&name))
                } else {
                    println!("{}", "Select new account:".cyan());
                    for (i, acc) in config.accounts.iter().enumerate() {
                        println!(
                            "  [{}] {} ({} - {:?})",
                            i + 1,
                            acc.name,
                            acc.username,
                            acc.platform
                        );
                    }
                    print!("\nEnter number (1-{}): ", config.accounts.len());
                    io::stdout().flush()?;
                    let mut input = String::new();
                    io::stdin().read_line(&mut input)?;
                    let choice: usize = input.trim().parse().unwrap_or(0);
                    if choice == 0 || choice > config.accounts.len() {
                        None
                    } else {
                        Some(&config.accounts[choice - 1])
                    }
                };

                if let Some(acc) = target {
                    let remote_output = Command::new("git")
                        .args(["remote", "get-url", "origin"])
                        .output();

                    let current_remote = match remote_output {
                        Ok(out) if out.status.success() => {
                            String::from_utf8_lossy(&out.stdout).trim().to_string()
                        }
                        _ => {
                            println!("{}", "✗ Could not read origin remote".red());
                            return Ok(());
                        }
                    };

                    let converted = convert_to_host(&current_remote, &acc.host_alias);
                    if let Err(err) = run_git(&["remote", "set-url", "origin", &converted]) {
                        println!("{}", "✗ Failed to switch remote".red());
                        println!("   {}", err);
                        return Ok(());
                    }

                    if let Err(err) = set_git_config(&acc.username, &acc.email) {
                        println!(
                            "{}",
                            "✗ Remote switched, but git config update failed".red()
                        );
                        println!("   {}", err);
                        return Ok(());
                    }

                    println!("{}", "✓ Remote switched".green());
                    println!("  origin     = {}", converted);
                    println!("  user.name  = {}", acc.username);
                    println!("  user.email = {}", acc.email);
                }
            }
        },

        Commands::Export => {
            let config = load_config();
            let content = serde_json::to_string_pretty(&config)?;
            println!("{}", content);
        }

        Commands::Import { file } => {
            let input = if let Some(path) = file {
                fs::read_to_string(path)?
            } else {
                let mut buffer = String::new();
                io::stdin().read_to_string(&mut buffer)?;
                buffer
            };

            let config: GityConfig = match serde_json::from_str(&input) {
                Ok(cfg) => cfg,
                Err(err) => {
                    eprintln!("{} Invalid JSON: {}", "✗".red(), err);
                    return Ok(());
                }
            };

            if let Err(err) = validate_accounts(&config.accounts) {
                eprintln!("{} Import rejected: {}", "✗".red(), err);
                return Ok(());
            }

            save_config(&config)?;
            update_ssh_config(&config.accounts)?;
            println!(
                "{} Imported {} account(s)",
                "✓".green(),
                config.accounts.len()
            );
            println!(
                "{}",
                "  Note: import restores config only; SSH key files must exist separately."
                    .yellow()
            );
        }

        Commands::Remove { name } => {
            let mut config = load_config();
            if config.accounts.is_empty() {
                println!("{}", "No accounts to remove".red());
                return Ok(());
            }

            let target_name = if let Some(n) = name {
                if config.accounts.iter().any(|a| a.name == n) {
                    Some(n)
                } else {
                    println!("{}", format!("Account '{}' not found", n).red());
                    return Ok(());
                }
            } else {
                println!("{}", "Select account to remove:".cyan());
                for (i, acc) in config.accounts.iter().enumerate() {
                    println!(
                        "  [{}] {} ({} - {:?})",
                        i + 1,
                        acc.name,
                        acc.username,
                        acc.platform
                    );
                }
                print!("\nEnter number (1-{}): ", config.accounts.len());
                io::stdout().flush()?;
                let mut input = String::new();
                io::stdin().read_line(&mut input)?;
                let choice: usize = input.trim().parse().unwrap_or(0);
                if choice == 0 || choice > config.accounts.len() {
                    println!("{}", "Invalid selection".red());
                    return Ok(());
                }
                Some(config.accounts[choice - 1].name.clone())
            };

            if let Some(n) = target_name {
                print!(
                    "{} Are you sure? This will remove the account from gity [y/N]: ",
                    "⚠".yellow()
                );
                io::stdout().flush()?;
                let mut confirm = String::new();
                io::stdin().read_line(&mut confirm)?;
                if confirm.trim().to_lowercase() != "y" {
                    println!("{}", "Cancelled".yellow());
                    return Ok(());
                }

                config.accounts.retain(|a| a.name != n);
                save_config(&config)?;
                update_ssh_config(&config.accounts)?;

                println!("{}", format!("✓ Account '{}' removed", n).green());
                print!("Delete SSH key files too? [y/N]: ");
                io::stdout().flush()?;
                let mut delete_keys = String::new();
                io::stdin().read_line(&mut delete_keys)?;

                if delete_keys.trim().eq_ignore_ascii_case("y") {
                    match delete_account_keys(&n) {
                        Ok(paths) if paths.is_empty() => {
                            println!("{}", "  No SSH key files were found to delete".yellow());
                        }
                        Ok(paths) => {
                            println!("{}", "  Deleted SSH key files:".green());
                            for path in paths {
                                println!("  - {}", path.display());
                            }
                        }
                        Err(err) => {
                            println!("{}", "  Failed to delete SSH key files".red());
                            println!("   {}", err);
                        }
                    }
                } else {
                    println!("{}", "  SSH key files were left untouched".yellow());
                }
            }
        }
    }

    Ok(())
}

fn convert_to_host(url: &str, host_alias: &str) -> String {
    let url = url.trim().trim_end_matches(".git").to_string();

    if url.starts_with("git@") {
        if let Some(path) = url.strip_prefix("git@") {
            if let Some((_host, rest)) = path.split_once(':') {
                return format!("{}:{}", host_alias, rest);
            }
        }
    }

    if url.starts_with("https://") || url.starts_with("http://") {
        let path = url
            .strip_prefix("https://")
            .or(url.strip_prefix("http://"))
            .unwrap_or(&url);
        let parts: Vec<&str> = path.split('/').filter(|s| !s.is_empty()).collect();
        if parts.len() >= 2
            && (parts[0].contains("github.com")
                || parts[0].contains("gitlab.com")
                || parts[0].contains("codeberg.org")
                || parts[0].contains("bitbucket.org"))
        {
            let repo = parts[1..].join("/");
            return format!("{}:{}", host_alias, repo);
        }
    }

    if !url.contains('@') && !url.starts_with("http") {
        if url.contains("github.com/")
            || url.contains("gitlab.com/")
            || url.contains("codeberg.org/")
            || url.contains("bitbucket.org/")
        {
            let parts: Vec<&str> = url.split('/').collect();
            let idx = parts.iter().position(|p| {
                p.contains("github.com")
                    || p.contains("gitlab.com")
                    || p.contains("codeberg.org")
                    || p.contains("bitbucket.org")
            });
            if let Some(i) = idx {
                let repo = parts[i + 1..].join("/");
                return format!("{}:{}", host_alias, repo);
            }
        }
        format!("{}:{}", host_alias, url)
    } else {
        url.to_string()
    }
}

fn set_git_config(username: &str, email: &str) -> io::Result<()> {
    run_git(&["config", "user.name", username])?;
    run_git(&["config", "user.email", email])?;
    Ok(())
}

fn run_git_remote_add(url: &str) -> io::Result<()> {
    match run_git(&["remote", "add", "origin", url]) {
        Ok(_) => Ok(()),
        Err(add_err) => match run_git(&["remote", "set-url", "origin", url]) {
            Ok(_) => Ok(()),
            Err(set_err) => Err(io::Error::other(format!(
                "{}; fallback set-url also failed: {}",
                add_err, set_err
            ))),
        },
    }
}

fn delete_account_keys(name: &str) -> io::Result<Vec<PathBuf>> {
    let ssh_dir = get_ssh_dir();
    let key_name = format!("id_ed25519_{}", name);
    let paths = [
        ssh_dir.join(&key_name),
        ssh_dir.join(format!("{}.pub", key_name)),
    ];

    let mut deleted = Vec::new();
    for path in paths {
        if path.exists() {
            fs::remove_file(&path)?;
            deleted.push(path);
        }
    }

    Ok(deleted)
}

fn print_result(remote: &str, username: &str, email: &str) {
    println!();
    println!("{}", "✓ Done!".green().bold());
    println!("  Remote:  {}", remote.green());
    println!("  user:    {}", username);
    println!("  email:   {}", email);
}

#[cfg(test)]
mod tests {
    use super::convert_to_host;

    #[test]
    fn converts_https_provider_url_to_host_alias() {
        let converted = convert_to_host("https://github.com/acme/project.git", "github-work");
        assert_eq!(converted, "github-work:acme/project");
    }

    #[test]
    fn converts_ssh_provider_url_to_host_alias() {
        let converted = convert_to_host("git@github.com:acme/project.git", "github-work");
        assert_eq!(converted, "github-work:acme/project");
    }

    #[test]
    fn converts_plain_owner_repo_to_host_alias() {
        let converted = convert_to_host("acme/project.git", "github-work");
        assert_eq!(converted, "github-work:acme/project");
    }

    #[test]
    fn preserves_non_provider_urls() {
        let converted = convert_to_host("ssh://git@example.com/acme/project.git", "github-work");
        assert_eq!(converted, "ssh://git@example.com/acme/project");
    }

    #[test]
    fn converts_existing_alias_to_new_alias() {
        let converted = convert_to_host("git@github-old:acme/project.git", "github-work");
        assert_eq!(converted, "github-work:acme/project");
    }

    #[test]
    fn converts_provider_path_without_scheme() {
        let converted = convert_to_host("github.com/acme/project.git", "github-work");
        assert_eq!(converted, "github-work:acme/project");
    }
}
